chore: RHIF-129 - Adapt to using useChrome
RedHatInsights/sed-frontend pull request #191
Opened 2023-03-22 21:49 UTC by bastilian

# Description

Associated Jira ticket: # (issue)

Please include a summary of the change, what this fixes/creates/improves.

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

2023-03-23 13:01 UTC, jmbuscemi commented
tagging @RedHatInsights/teamnado for their awareness and can help out with activation key functionality as needed.
our QE team can also run our IQE regression tests once this is in Stage

2023-03-27 11:31 UTC, gkarat reviewed
LGTM! Works well locally without any errors/warnings. I am not really acquainted to the app so the comments are really minor. Probably a good idea to have another look from one of the active maintainers too

2023-03-27 11:31 UTC, gkarat commented on src/Components/Authentication/Authentication.js
> +    isSuccess && chrome?.hideGlobalFilter();
nit-pick: this should add more bit of safety by preventing calling `undefined` as a func if `hideGlobalFilter` is not defined
```suggestion
    isSuccess && chrome?.hideGlobalFilter?.();
```

2023-03-27 11:31 UTC, gkarat commented on src/Components/Authentication/Authentication.js
> +    return <></>;
Can't we return the Loading component instead? Is empty component a good solution for this case?

2023-03-27 11:31 UTC, gkarat commented on src/utils/platformServices.js
> +      return chrome?.auth?.getUser();
the same suggestion here:
```suggestion
      return chrome?.auth?.getUser?.();
```

2023-03-27 11:45 UTC, bastilian commented on src/Components/Authentication/Authentication.js
> +    return <></>;
It's now returning the `<Loading />` component.

2023-03-27 11:47 UTC, jlgre requested changes
It looks like all of the mutation queries are failing (ex. delete, addadditionalrepos, create, etc) - I think something is wrong with how the token is being passed to those because the requests have `Bearer undefined` in them.

I also mentioned this in slack but will mention it here too - the hook tests shoud be updated to mock the `useUser` hook - instead of mocking `window.insights.chrome.user`. I imagine these still pass because that is what those hooks look at under the hood - but we should change it now in case the implementation details of chroming changes.

2023-03-28 11:50 UTC, bastilian commented
@jlgre Thank you for taking a look! I went over it again and things should now be in order and working properly.

2023-03-28 13:46 UTC, jlgre reviewed
A couple more comments. That mock looks good now, but the tests it affects (most things in the `hooks/__tests__/` dir should be able to have their `window.insights.chrome.auth` definitions removed.

2023-03-28 13:46 UTC, jlgre commented on src/hooks/__tests__/useUser.test.js
> +  }),
Does this mock need to stay if its done in `config/setupTests.js`?

2023-03-28 13:46 UTC, lukegrn commented on src/hooks/useActivationKey.js
>  };
Is there a reason these functions are curried instead of just being defined as `const getActivationKey = (token, keyName) => { ... }`?

I'm only going to make this comment in the one spot - but every hook looks like it is like this.

2023-03-28 14:19 UTC, bastilian commented on src/hooks/__tests__/useUser.test.js
> +  }),
Yeah, in these tests there are expectations that the default mock in `setupTests.js` would not fulfil.

2023-03-28 14:25 UTC, jlgre commented on src/hooks/__tests__/useUser.test.js
> +  }),
Perfect - thanks!

2023-03-28 14:26 UTC, bastilian commented on src/hooks/useActivationKey.js
>  };
It is primarily to be consistent across `useQuery` and `useMutation` on how the token is passed. I tried a few things, but they would have been a bit more all over the place with `react-query` version 3. 

There would be a way with version 4, where the token could be passed along via the `meta` option, which would work for both by using some wrapper hook that injects chrome.

2023-03-28 14:29 UTC, bastilian commented
@jlgre Oh, Yeah! I overlooked those `window.insights` definitions. I'll remove them!

2023-03-28 14:41 UTC, jlgre commented on src/hooks/useActivationKey.js
>  };
Perfect - that makes sense. Thanks!

2023-04-06 11:45 UTC, bastilian commented
@jlgre The PR to add the hook used here is now pending review. Once it is merged and a new package version has been pushed, i'll bump the package here and the test should pass and this PR should then be ready for a final review.

2023-04-06 15:38 UTC, jlgre commented
> @jlgre The PR to add the hook used here is now pending review. Once it is merged and a new package version has been pushed, i'll bump the package here and the test should pass and this PR should then be ready for a final review.

Ack - I'll look today. So the Travis check is expected to be failing right now?

2023-04-06 20:31 UTC, jlgre approved these changes
This looks good to me providing that test failure is expected right now

2023-04-12 09:50 UTC, bastilian commented
@jlgre This should now be ready to get merged. I did click through it after the utils package upgrade, but I'd feel more comfortable if someone more familiar would take a final quick look and merge it.

2023-04-12 15:08 UTC, merged