fix(Authentication): ESSNTL-5018 - Show "Not Authorised" with no permissions
RedHatInsights/sed-frontend pull request #259
Opened 2023-08-17 14:37 UTC by bastilian

# Description

Associated Jira ticket: #ESSNTL-5018 (issue)

This lifts up the RBAC check in sed-frontend in order to avoid querying the API with an account that doesn't have (any) permissions.

# How to test the PR

1) Create an account with no roles/permissions assigned (related to RHC)
2) Verify RHC shows the "Not authorised page"

# Checklist:

- [x] The commit message has the Jira ticket linked
- [x] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

2023-08-23 08:25 UTC, AsToNlele reviewed
This works great, with no roles I see the "You do not have access...".

When I add the RHC viewer role and have no other roles, the page loads as expected, but I get this error:
![image](https://github.com/RedHatInsights/sed-frontend/assets/20592948/38f35f0d-d2cd-4316-9fa3-69e1908c5dec)

When I add Inventory Hosts Read, I get no error notification.

Not sure if this is expected, but this might be out of the scope for this ticket

2023-08-23 12:01 UTC, bastilian commented
@AsToNlele Thanks for testing and reviewing! The `Authentication` component is now lifted up to the `AppEntry` component and should now prevent any API calls.

2023-09-04 10:58 UTC, gkarat requested changes

2023-09-04 10:58 UTC, gkarat commented on src/AppEntry.js
> +        <Authentication>
This should be wrapped in QueryClientProvider. Right now, if you open /insights/connector, you get
```
No QueryClient set, use QueryClientProvider to set one
```

2023-09-04 11:28 UTC, gkarat requested changes

2023-09-04 11:28 UTC, gkarat commented on src/Routes.js
> +        path={paths.connector}
I am not sure how exactly this PR is causing it, but if I navigate by clicking on "View log" in the upper top corner, I get an error
```
(0 , react_router_dom__WEBPACK_IMPORTED_MODULE_4__.useHistory) is not a function
```

2023-09-04 11:28 UTC, gkarat commented on src/Routes.js
> +        path={paths.connector}
it's not reproducible on stage c.r.c. (master version)

2023-09-04 15:00 UTC, gkarat approved these changes
LGTM! the previous issues seem to be resolved, and it worked nicely locally... thanks @bastilian

2023-09-04 15:46 UTC, merged